### ISSUE TITLE
The font "TrajanPro" cannot be found.

### ISSUE THREAD

**Issue by Ginso** [poet-of-the-fall/carddivider#13]
Hello,
i tried to create the pdf using TexStudio + MikTeX and get the error:

Package fontspec Error: The font "TrajanPro" cannot be found.

any ideas?

**Comment by bin101** [comment]
Install the font. The link is inside the README.

**Comment by poet-of-the-fall** [comment]
Look here:
https://www.wfonts.com/font/trajan-pro
