### ISSUE TITLE
Renaissance available

### ISSUE THREAD

**Issue by bin101** [poet-of-the-fall/carddivider#16]
Hi,

Renaissance is already available. Do you have any plans when you are going to add this?

Regards,
bin101

**Comment by poet-of-the-fall** [comment]
Yes, unfortunately there is no download on the dominion-Welt website until now... so I ordered the game already and will probably add it this week 😉

**Comment by bin101** [comment]
Thank for the fast answer :)

**Comment by poet-of-the-fall** [comment]
Done and merged to master. Could someone please check for typos and so on because this time I needed to type the whole text as there was nothing available online for copy&paste the text...
