### ISSUE TITLE
blacklandscape.tex doesn't render same black colour values when printing

### ISSUE THREAD

**Issue by patrickkulling** [poet-of-the-fall/carddivider#18]
When printing the cards_de_all_landscape.pdf file, the cards background doesn't appear as a "pitchblack" colour value, but rather a dark grey one. This is especially noticable with the banner & other icon graphics on top, because they render a pitchblack colour.

I have tried different printer settings and workarounds related to [this issue](https://tex.stackexchange.com/questions/397703/black-background-is-not-as-black-as-black-text) with  lualatex and other engines, but couldn't find a solution yet. When switching the `framebg` colour value to something else than black, the printed result looks great.

A possible workaround could be to render a 1x1 pixel "pitchblack" png image instead of relying on the `fill=framebg` parameter.

see:
https://www.dropbox.com/s/c1mf52iprkwfie4/IMG_6098.JPG

**Comment by poet-of-the-fall** [comment]
Sorry for not answering to this issue in time...I just noticed that there is one 🙈
I also slightly noticed this on my printer, but I think this as well depending on the printer and drivers used...feel free to compile a version with `framebg` like `{1,1,1}`, maybe this helps already. I won't fix this as I'm not an export on printers. If there's someone who can help me doing this right, please just reopen this issue.
