### ISSUE TITLE
Drucken via printerstudio.de

### ISSUE THREAD

**Issue by bin101** [poet-of-the-fall/carddivider#21]
Hallo,

ich würde gerne die Trenner für den privaten Gebrauch bei printerstudio.de drucken lassen.

Da das Format der Trenner so nicht existiert, würde ich auf die Tarot Vorlage ausweichen und dann die Trenner Zuhause selbst mit der Dahle zurecht schneiden und anschließend die neuen Ecken runden.

Hier gäbe es die Vorlage, wie eine Seite der pdf aussehen müsste:
https://www.printerstudio.de/dl/templates/playingcard/tarot-size.pdf

Ein User aus dem Dominion-Welt Forum hat das auch schon so gemacht:
http://forum.dominion-welt.de/viewtopic.php?f=7&t=1039

Vorteil bei printerstudio.de wäre 1. Günstiger und 2. Bieten die auch Kunstoff Karten an. 

Wäre es möglich, dass du ein weiteres Format dafür anlegst?

**Comment by poet-of-the-fall** [comment]
Ja, das lässt sich sicher machen. Frage ist dann, wie das ganze exportiert werden sollte. Vermutlich sollen die Karten jeweils als eigenständiges Bild rauskommen. Da müsste ich schauen, wie man die Seiten entsprechend klein bekommt bzw. statt einem PDF mehrere PNGs erstellt...oder übersehe ich da gerade Funktionen bei printerstudio.de?

**Comment by bin101** [comment]
Man kann denen auch PDFs übergeben, würde dann aber zusätzliche Bearbeitungsgebühren verursachen. Ich denke dann, dass jemand von denen dann ein Skript anschmeißt, welches die Konvertierung nach jpg, jpeg, bmp, png, gif, tif oder tiff vornimmt.
Daher wäre direkt eine Ausgabe nach png im geforderten Format für Taro Karten:

> Wir akzeptieren jpg, jpeg, bmp, png, gif, tif und tiff
> Min. Größe 897 x 1497 pixels (300DPI) | Max Dateigrösse 32MB

pro Karte dann wohl am günstigsten.

**Comment by poet-of-the-fall** [comment]
OK, ich hab das mal im [tarot-format branch](https://github.com/poet-of-the-fall/carddivider/tree/tarot-format) gebastelt. Die PDF hab ich mal nicht hochgeladen, da wird das Repo dann recht groß (hat über 200MB). Deswegen bitte selber kompilieren. Den Export als PNG hab ich noch nicht geschafft, da bietet sich allerdings ImageMagick an, siehe z.B. den Beitrag: https://tex.stackexchange.com/questions/11866/compile-a-latex-document-into-a-png-image-thats-as-short-as-possible ( `\documentclass[convert]{standalone}
` hat bei mir nicht geklappt, deswegen leider der nicht so saubere commit).

Kannst du damit was anfangen?

**Comment by poet-of-the-fall** [comment]
Hab doch noch ne kleinere PDF rausbekommen und hinzugefügt.
Die einzelnen Bilder sind immer noch zu groß, um sie hier ins Repo zu packen, die liegen vorerst mal ohne Gewähr bei [Adobe](https://adobe.ly/2VE9PHV).

**Comment by bin101** [comment]
Sieht soweit für den ersten Test ganz gut aus :) Danke schon mal für die schnelle Umsetzung.
Latex-Workshop schmeißt bei mir merkwürdigerweise einen Fehler beim builden aber die pdf wird trotzdem, wenn auch mit mehreren weißen Seiten bzw. Seiten die nur 1sp enthalten, erstellt.

Da Latex wohl nicht mm genau arbeiten kann habe ich dann die png's mit 310dpi erstellt, sonst meckert printerstudio wegen einem fehlenden Pixel :(

Die Trenner würde ich mir dann Zuhause auf 105mm x 62mm zurechtschneiden wollen. Ich glaube das ist die Maße mit der oberen Schnittlinie bei deinem Hochkant Format. Dazu wären entsprechende Margins links und unten ganz gut, sodass man nur noch 2 Seiten beschneiden muss, wie der User aus dem dominion-welt forum. Link hatte ich ja schon oben geteilt.

Hier mal ein Testprojekt mit den ersten 10 Karten aus Renaissance:
https://tinyurl.com/Frist10Renaissance

Man sieht, dass die Zipfel des Kartentitel-Banners und das Erweiterungs-Logo etwas aus dem Sicherheitsbereich herausragt aber das Risiko würde ich eingehen. So wäre auf jeden Fall der schwarze Rand oben und rechts gleich breit.

Als kleines Extra-Feature wäre es natürlich toll, wenn der User in der card.tex selbst seine endgültigen Maße, welche er nach manuellen Beschnitt erreichen möchte, angeben kann und dann die Margins automatisch gesetzt werden, sodass er dann auch nur noch 2 Seiten beschneiden muss und trotzdem überall einen gleich breiten Rand hat.

**Comment by poet-of-the-fall** [comment]
Ja, ich glaube insgesamt ist das ganze Dokument nicht super schön geschrieben, die Fehler fliegen auch bei mir. Die weißen Seiten hab ich mal reduziert, die kommen von den ganzen Seitenumbrüchen bei den einzelnen Sets. Das ganze war ja grundsätzlich auf A4 und automatische Verteilung auf der Seite ausgelegt, nicht auf das eigene Format 😉 

Nachdem ich das Format eh nicht sauber im Master integrieren kann, hab ich hier mal etwas rumgerutscht. In der `cards.txt` sind jetzt 
```
\setlength{\paperwidth}{75.9mm}
\setlength{\paperheight}{126.7mm}
\setlength{\padding}{6.1mm}
\setlength{\paddingtop}{21.0mm}
```
zum steuern der Seitengröße und des internen Abstands. Letztlich hab ich das nur aus `format/blackportrait_tarot` herausgezogen. Alle weiteren Einstellungen zum Layout kann man dort machen. 
Woher die unterschiedlichen Randabstände kommen weiß ich gerade nicht, evtl ist auch das Onlinetool nicht genau was das angeht. Du kannst auch gerne in der `format/blackportrait_tarot` Datei rumspielen und dir eigene Abstände für jede Seite setzen bzw. das Layout komplett ändern. Layout und Inhalt sind ja zum Glück in unterschiedlichen Dateien 😉
