### ISSUE TITLE
Kurzformat zum ausdrucken mit möglichst wenig Papier

### ISSUE THREAD

**Issue by ebinski** [poet-of-the-fall/carddivider#27]
Hallo,

erstmal ein dicken Daumen hoch und Danke schön für die tolle Arbeit, die in dieses Projekt floss/fließt.
Mir ist bei den PDF's aufgefallen, dass es nur die Varianten gbt, die alles und vollkommmen ausdrucken.
Gibt es auch eine Variante (vielleicht auch von anderen Usern), die nur die Kartenteiler nacheinander auflistet? Also ohne Umbrüche zwischen den Erweiterungen? Am besten auch ohne "Platzhalter", "Empfohlene 10er Sätze", "Anleitung" und ohne doppelte (Kupfer, Silber, Gold, Anwesen, Herzogtum, Provinz und Fluch). Ihc glaube das würde die 150 Seiten doch noch um einige Seiten verringern und die Umwelt ein wenig schonen.

Gibt es da eine Variante? Hat jemand soetwas schon ungesetzt?

Gruß ebinski

**Comment by poet-of-the-fall** [comment]
Prinzipiell sollte es reichen, in jeder Datei die Zeilen
```
\clearpage
\newpage
```
zu löschen, allerdings ist dann das Layout evtl. etwas kaputt. Außerdem sollte man dann natürlich die nicht benötigten Sets auskommentieren. So eine Version habe ich aber bisher nicht erstellt, da ich dachte, die meisten drucken eh nur die Seiten der benötigten Sets aus...

**Comment by ebinski** [comment]
Das habe ich auch schon gemacht, allerdings werden dann nicht hintereinander weg die Karten "geplottet", sondern lediglich der Seitenumbruch verhindert. 
Beispielsweise gibt es ja den Fluch aus den "basecard.tex" in einer Zeile als einzige Karte, obwohl dort noch locker 2 Karten in diese Zeile passen würden. Die Karten die nach Fluch dann eingefügt werden, weden immer in einer neuen Zeile zugefügt, wenn auch nicht in einer neuen Seite, aber in einer neuen Zeile.
Derzeit bekomme ich es auch nicht besser hin..

**Comment by ebinski** [comment]
Ok, ich habe jetzt das Problem gefunden. Da ich ein Noob in LaTex bin wusste ich das nicht.
Es liegt an den eingefügten und nicht auskommentierten Zeilen im .tex-Code des jeweiligen Sets. Dadurch wurden quasi immer kleine nicht sichtbare Zeilenumbrüche eingefügt, wodurch eine Aneinanderreihung der Karten verhindert wurde. Selbst wenn 
`\section` `\clearpage` `\newpage` entfernt wurden.
