### ISSUE TITLE
Blütezeit & Hinterland 2. Edition, sowie Blütezeit 2. Edition Updatepack

### ISSUE THREAD

**Issue by Ultram11** [poet-of-the-fall/carddivider#30]
Hi zusammen, poet-of-the-fall,

vielen Dank für die fantastische Arbeit die hier bereits geleistet wurde.

Wird zufällig bereits am hinzufügen der Blütezeit & Hinterland 2. Edition, sowie Blütezeit 2. Edition Updatepack gearbeitet? Diese sind ja bereits erschienen und haben einige Änderungen an Karten mit sich gebracht.
Die Anleitung mit den Änderungen ist bereits auf Dominion-Welt zur Verfügung gestellt. 
[Blütezeit 2. Edition](https://www.dominion-welt.de/wp-content/uploads/S220084DomBluet2nED_SR_LowRes.pdf)
[Hinterland 2. Edition](https://www.dominion-welt.de/wp-content/uploads/S220163DomHint2ndD_SR_LowRes.pdf)
[Blütezeit 2. Edition Updatepack](https://www.dominion-welt.de/wp-content/uploads/S220084DomBluet2nED_SR_LowRes.pdf)

Mir ist auch noch aufgefallen das es einen Rechtschreibfehler in der Herzogin Karte der _Erweiterung V - Hinterland (Rio Grande Games 2020)_ gibt. Im Text sollte die Mehrzahl einer Herzogin mit zwei **n** geschrieben werden. 

Danke und Grüße

**Comment by poet-of-the-fall** [comment]
Hallo @Ultram11 
Ja, die Erweiterungen stehen schon auf der Todo Liste. Mit Hinterland hab ich lokal auch schon angefangen, aktuell aber leider zu wenig Zeit gehabt. Da ich die aber selber auch brauche, werden sie bald kommen ;-)

**Comment by Ultram11** [comment]
Hi @poet-of-the-fall ,

das sind doch gute Neuigkeiten. Danke dir. Dann bleib ich einfach geduldig.

**Comment by poet-of-the-fall** [comment]
Hi @Ultram11, ich habe gerade die neuen Erweiterungen ergänzt. Viel Spaß beim drucken, ausschneiden und spielen 😉

**Comment by Ultram11** [comment]
Hi @poet-of-the-fall , vielen Dank für deine Arbeit. Hab ich übers Wochenende was zu tun.
