### ISSUE TITLE
VS Code Error: Skipping undefined tool "latexmk" in recipe "latexmk."

### ISSUE THREAD

**Issue by FEmser** [poet-of-the-fall/carddivider#34]
Hi, ich habe die Anleitung zur Installation von LaTeX-Workshop in VS Code durchgeführt und TeX Live installiert.
Leider hat mir VS Code beim Kompilieren immer den Fehler "Skipping undefined tool "latexmk" in recipe "latexmk."" genannt.
Ich habe versucht, auf LuaLatex umzustellen, aber scheinbar ist irgendwo latexmk als Standard angegeben...

Gelöst werden konnte das Problem indem in der `Settings.js` folgende Zeile hinzugefügt wird:

`"latex-workshop.latex.build.forceRecipeUsage": false,`

Quelle und Infos:
https://www.joelotz.com/blog/2022/enabling-different-latex-compilers-in-vs-code.html

**Comment by poet-of-the-fall** [comment]
Ah danke 😊 
Hab beim Laptopwechsel wieder Text Studio verwendet und das nicht gemerkt. Zeile ist hinzugefügt, teste ich dann beim Hinzufügen der nächsten Extension gleich mal 😉
