### ISSUE TITLE
Intrige-Editionen vertauscht

### ISSUE THREAD

**Issue by elyastarg** [poet-of-the-fall/carddivider#7]
Die beiden Editionen von der Intrige sind vertauscht / enthalten jeweils gerade die falschen der geänderten Karten.

**Comment by poet-of-the-fall** [comment]
Sicher? Ich habe eben noch mal mit meiner Version (Rio Grande Games) verglichen und die stimmt mit der in der PDF überein. Welche hast du?

**Comment by elyastarg** [comment]
Ich habe die alte Hans-im-Glück-Ausgabe (ca. 2009). Dort gab es noch folgende Karten:
Geheimkammer, Grosse Halle, Kupferschmied, Saboteur, Späher, Tribut

Für die Second Edition (2016) wurden diese Karten ersetzt durch:
Höflinge, Mühle, Austausch, Patrouille, Diplomatin, Geheimgang, Herumtreiberin

Vermutlich hat Rio Grande von 2013 bis 2016 auch die alte Version der Intrige vertrieben (als einfachen Nachdruck), und so eine scheinst du zu besitzen.

Siehe z.B. auch https://brettspielpoesie.de/dominion-ergaenzungs-set-basisspiel-die-intrige-5892/

**Comment by elyastarg** [comment]
Das heisst bei näherer Betrachtung sind nicht die zwei Editionen vertauscht, sondern die Second Edition  der Intrige fehlt und die alte HiG-Version führt fälschlicherweise deren Karten auf.

**Comment by poet-of-the-fall** [comment]
Ah OK, das letzte kann sein. Da ich die alter Version nicht habe, habe ich das direkt von Eiko übernommen. Ich benenn das mal um. Danke für den Hinweis!

**Comment by elyastarg** [comment]
Nichts für ungut, aber das ist jetzt eindeutig falscher als vorher. "Edition II" war schon der richtige Titel für die 2009er-HIG-Ausgabe! Nur gibt es die Karten

> Höflinge, Mühle, Austausch, Patrouille, Diplomatin, Geheimgang, Herumtreiberin

eben erst seit 2017, als Rio Grande die "Second Edition" der Intrige veröffentlicht hat (analog zur "Second Edition" des Grundspiels). HiG hat 2009 zwar die Intrige als "Edition II" und nicht als "Erweiterung" veröffentlicht (da eigenständig spielbar, das ursprüngliche Basisspiel war "Edition I"), aber das hat nichts mit der Second Edition zu tun! Diese Ausgabe enthielt damals genau wie die erste bei Rio Grande erschienene Ausgabe der Intrige die Karten

> Geheimkammer, Grosse Halle, Kupferschmied, Saboteur, Späher, Tribut.

Ob man diese Ausgaben im PDF deswegen überhaupt beide aufführen will, weiss ich nicht (wobei es z.B. Seaside ja auch einfach doppelt gibt), aber was auf alle Fälle fehlt, ist der Kartensatz "Second Edition - Die Intrige (2017)" - dort gehören die Karten "Höflinge, etc." hin! (Zusätzlich hat Rio Grande 2017 ja fairerweise auch das Ergänzungsset mit den 7 neuen Basis- und Intrige-Karten rausgebraucht, diese sind auch korrekt aufgelistet.)

Sorry fürs Rummäkeln :-), und vielen Dank für deinen Einsatz!

**Comment by poet-of-the-fall** [comment]
Ok, danke für die ausführliche Erklärung, ich schau mir das dieses Wochenende mal mit etwas mehr Ruhe an 😉 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by poet-of-the-fall** [comment]
OK, ich hab mir das noch mal angeschaut. Ich hab da wohl damals was durchgewinkt und nicht weiter angeschaut, was ich nicht selbst gemacht habe. 

@elyastarg was meinst du, passt das jetzt so? 
Wir haben jetzt die Edition 2 von HIG, die erste Version von RGG und das Update von RGG.

**Comment by elyastarg** [comment]
Jetzt sieht's richtig aus im Sinne meiner Anmerkungen oben. Cool, vielen Dank!

ABER: Mittlerweile habe ich herausgefunden, dass die Second Edition der Intrige gar nie auf Deutsch erschienen ist (!). Die Karten
> Höflinge, Mühle, Austausch, Patrouille, Diplomatin, Geheimgang, Herumtreiberin

sind auf Deutsch also *nur* im Ergänzungsset enthalten (und sind so auch schon länger korrekt aufgelistet im PDF).

D.h. den ganzen Kartensatz "Second Edition - Intrige" sollte man wieder löschen, weil dieser im deutschen Markt so gar nie veröffentlicht wurde (im Unterschied zu überall sonst!!!). Sorry, das war mir echt nicht bewusst (und habe ich auch nur durch Zufall herausgefunden).

[Quelle ist amazon.de](https://www.amazon.de/Rio-Grande-Games-22501402-Erweiterung/dp/B00IPAR7VW/)

> Frage: Ist das die erste oder die zweite version der intrige? sind hier also die neuen karten enthalten?
> 
> Antwort: Hallo, es ist richtig, dass dies die Version von Rio Grande Games ist und es eine frühere Version vom Verlag Hans im Glück gab. Jedoch vermuten wir, dass Sie die 2. Edition der Dominion Erweiterung "Intrige" meine, so wie sie z. B. in den USA erschienen ist. Diese Version ist in Deutschland nicht aufgelegt worden und wird voraussichtlich auch nicht aufgelegt werden. Um trotzdem in den Genuss der neuen Karten zu kommen, gibt es das Dominion Ergänzungs-Set mit den Update Karten für Basis und Intrige. Dieses finden Sie unter der Amazon Nummer: B06XDFZQ63.
> Wir hoffen, Ihnen damit weitergeholfen zu haben.
> Viel Spaß beim Spielen von Dominion! 
> Von ASS Altenburger Hersteller am 23. August 2018

**Comment by poet-of-the-fall** [comment]
Ja, ich hab. da auch auf Dominion-Welt.de nichts gesehen. Das ganze ließ sich ja einfach aus dem bisherigen Sachen Zusammenkopieren. Ich behalte mal Daten für die "Second Edition" (falls Sie doch zufällig noch kommt) aber blende sie einfach beim nächsten Update zu Dark Ages vorerst aus 😉
