### ISSUE TITLE
falsche Kosten beim Spion

### ISSUE THREAD

**Issue by elyastarg** [poet-of-the-fall/carddivider#8]
Beim Spion (Grundspiel) stehen fälschlicherweise Kosten von 5 (statt 4)

**Comment by poet-of-the-fall** [comment]
Fixed: https://github.com/poet-of-the-fall/carddivider/commit/530c2382e252cfef16fdb6ea83f209a42ce45196

PDFs erstell ich später nach dem alle Fehler korrigiert sind.
